config/routes.rb
Rails.application.routes.draw do


  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root 'frontend#index'

  get "/admin", to: "admin#index", as: :admin_root


  namespace :admin do 
    resources :projects
    resources :project_tags
    resources :project_categories
    resources :posts
    resources :post_categories
    resources :pages
    resources :opinions
  end

  get "/contact", to: "frontend#contact", as: :contact
  get "/about-me", to: "frontend#about", as: :about
  post "/contact", to: "frontend#send_contact", as: :send_contact
  resources :projects, only: [:index, :show]
  resources :posts, only: [:index, :show]
  resources :opinions, only: [:index, :show]
  resources :post_categories, only: [:show]

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/post.rb
class Post < ActiveRecord::Base

  mount_uploader :image, PostPhotoUploader

  default_scope { order('created_at DESC') }
   
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_and_belongs_to_many :post_categories

  self.per_page = 10
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name, use: :slugged
  has_and_belongs_to_many :posts
end

app/models/project.rb
class Project < ActiveRecord::Base

  mount_uploader :image, ProjectPhotoUploader
  default_scope { order('created_at DESC') }

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_and_belongs_to_many :project_tags
  has_and_belongs_to_many :project_categories
  has_many :project_images
  accepts_nested_attributes_for :project_images, :reject_if => :all_blank, :allow_destroy => true
end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name, use: :slugged
  has_and_belongs_to_many :projects
end

app/models/project_image.rb
class ProjectImage < ActiveRecord::Base

  mount_uploader :foto, ProjectUploader

  belongs_to :project
end

app/models/project_tag.rb
class ProjectTag < ActiveRecord::Base

  IMG = [
        "Sass" => "sass.png", 
        "jQuery" => "jquery.png", 
        "CoffyScript" => "coffy.png", 
        "WordPress" => "wordpress.png", 
        "PHP" => "php.png", 
        "AngularJs" => "angularjs.png",
        "Symfony 2" => "symfony.png",
        "Magento" => "magento.jpg", 
        "Ruby on Rails" => "rails.jpg",
        "Joomla" => "joomla.png",
        "Sinatra" => "sinatra.png",
        "PayU" => "payu.jpg",
        "MySql" => "mysql.png",
        "PostgreSQL" => "postgresql.png",
        "PayPal Api" => "paypal.jpg",
        "LinkedIn Api" => "linkedin.jpg", 
        "Google Maps Api" => "google-maps.png",
        "Amazon" => "amazon.jpg",
        "Android" => "android.png",
        "Bootstrap" => "bootstrap.jpg",
        "Capistrano" => "capistrano.png",
        "Cucumber" => "cucumber.png",
        "D3.js" => "d3js-logo.jpg",
        "DigitalOcean" => "do.jpg",
        "Fb API" => "fb-api.png",
        "Font Awesome" => "font-awesome-logo.png",
        "foundation" => "foundation.jpg",
        "Google Plus Api" => "google_plus_api.jpg",
        "Heroku" => "heroku.jpg",
        "jQuery Mobile" => "jquery-mobile.png",
        "Object C" => "objectc.jpg",
        "RSpec" => "rspec.jpg",
        "Ruby" => "ruby.png",
        "Sassu" => "sassu.jpg",
        "Spree" => "spree.jpg",
        "Stripe" => "stripe.png"
    ]

  extend FriendlyId
  friendly_id :name, use: :slugged
  has_and_belongs_to_many :projects
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	before_action :authenticate_user!
	before_action :check_permision!

	layout "admin"

	def index
	end

	protected

	def check_permision!
		unless current_user.has_role :admin
			redirect_to :root_path
		end
	end

end

app/controllers/amin_controller.rb
class AdminController < ApplicationController

	before_action :authenticate_user!
	before_action :check_permision

	def index
	end

	protected

	def check_permision!
		unless current_user.has_role :admin
			redirect_to :root_path
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  def index
    @posts = Post.all.limit(4)
    @opinions  = Opinion.all.limit(2)
  end

  def contact
    @contact = Contact.new
  end

  def send_contact
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to contact_path, notice: "Wiadomość wysłana"
    else
      render action: "contact"
    end
  end

  def about
    @tags = ProjectTag.all
  end

  protected 

  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController 

  def index
    @opinions = Opinion.all
  end

  def show
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 

  def index
    @posts = Post.paginate(:page => params[:page])
  end

  def show
    @post = Post.friendly.find(params[:id])  
  end

  

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show]

  def index 
    @projects = Project.all
    @categories = ProjectCategory.all
    @tags = ProjectTag.all
  end

  
  def show
  end

  protected

  def set_project
    @project = Project.friendly.find(params[:id])  
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_link_to(options = {}, html_options = {}, &block)
    active_class = html_options[:active] || "active"
    html_options.delete(:active)
    html_options[:class] = "#{html_options[:class]} #{active_class}" if current_page?(options)

  end

  def tag_to_img(tag)
    image_tag ProjectTag::IMG[0][tag], title: tag, alt: tag
  end
end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/views/admin/index.html.haml
admin

app/views/admin/pages/_form.html.haml
= simple_form_for [:admin, @page], :html => {class: "form-horizontal"} do |f|
  .form-group
    = f.label :title, class: "col-sm-2 control-label"
    .col-sm-10
      = f.input_field :title, label: false, class: "form-control"
  - if @page.id.present?
    .form-group
      = f.label :slug, class: "col-sm-2 control-label"
      .col-sm-10
        = f.input_field :slug, label: false, class: "form-control"
  .form-group
    = f.label :description, class: "col-sm-2 control-label"
    .col-sm-10
      = f.input_field :description, label: false, class: "form-control"
  .form-group
    = f.label :keywords, class: "col-sm-2 control-label"
    .col-sm-10
      = f.input_field :keywords, label: false, class: "form-control"
  .form-group
    = f.label :content, class: "col-sm-2 control-label"
    .col-sm-10
      = f.input_field :content, label: false, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.button :submit, "Zapisz" , class: "btn btn-default"

app/views/admin/pages/index.html.haml
= link_to "Dodaj stronę", new_admin_page_path, class: "btn btn-success"

%table.table
  %thead
    %tr
      %th Nazwa
      %th Link
      %th
  %tbody
    - @pages.each do |pt|
      %tr
        %td= pt.title
        %td= pt.slug
        %td{style: "width: 200px;"}
          -link_to raw(t('buttons.show_icon')), admin_page_path(pt), class: 'btn btn-default'
          =link_to raw(t('buttons.edit_icon')), edit_admin_page_path(pt), class: 'btn btn-success'
          =link_to raw(t('buttons.delete_icon')), admin_page_path(pt), method: :delete, data: { confirm: t('destroy.page') }, class: 'btn btn-danger'

app/views/layouts/_footer.html.haml
%footer#footer
  .container
    .row
      .footer-ribon
        %span= t('footer.header')
      .col-md-4
        .newsletter
          %h4 Newsletter
          %p Bądź zawsze na czasie. Podaj imię oraz email by zasubskrybować newsletter.
          %form.form{:method=>"POST", :action=>"https://www.benefiter.pl/save_user_form/", :target=>"_top" }
            .form-group
              %input{ :type=>"hidden", :name=>"aid", :value=>"19087"}    
              %input#email.form-control.col-md-12.col-sm-12{:name => "name", :placeholder => "Imię", :type => "text"}/
            .form-group
              %input#email.form-control.col-md-12.col-sm-12{:name => "email", :placeholder => "Adres email", :type => "text"}/
              %input{:name => "custom1", :type => "hidden", :value => ""}/
              %input{:name => "custom2", :type => "hidden", :value => ""}/
              %input{:name => "custom3", :type => "hidden", :value => ""}/
              %input{:name => "custom4", :type => "hidden", :value => ""}/
              %input{:name => "custom5", :type => "hidden", :value => ""}/
            .input-group
              %button.btn.btn-danger{:type => "submit"} Zapisz!    
      .col-md-5
        .contact-details
          %h4 Kontakt
          %ul.contact
            %li
              %p
                %i.icon.icon-phone
                %strong Telefon:
                790 691 371
            %li
              %p
                %i.icon.icon-envelope
                %strong Email:
                %a{:href => "mailto:mail@example.com"} przemek.4mm@gmail.com
      .col-md-3
        %h4= t('footer.follow')
        .social-icons
          %ul.social-icons
            %li.facebook
              %a{"data-placement" => "bottom", :href => "http://www.facebook.com/olesinski.przemyslaw", :rel => "tooltip", :target => "_blank", :title => "Facebook"} Facebook
            %li.googleplus
              %a{"data-placement" => "bottom", :href => "http://plus.google.com/+PrzemysławOlesiński/", :rel => "Google+", :target => "_blank", :title => "Google+"} Google +
            %li.linkedin
              %a{"data-placement" => "bottom", :href => "http://www.linkedin.com/in/przemyslawolesinski/", :rel => "tooltip", :target => "_blank", :title => "Linkedin"} Linkedin
  .footer-copyright
    .container
      .row
        .col-md-8
          %p © Copyright 2014. Wszystkie prawa zastrzeżone.
        .col-md-4
          %nav#sub-menu
            %ul
              %li
                = link_to "Mapa Strony", "#"
              %li
                = link_to "Kontakt", contact_path

app/views/layouts/_nav.html.haml
%header
  .container
    %button.btn.btn-responsive-nav.btn-inverse{"data-target" => ".nav-main-collapse", "data-toggle" => "collapse"}
      %i.icon.icon-bars
  .navbar-collapse.nav-main-collapse.collapse
    .container
      .social-icons
        %ul.social-icons
          %li.facebook
            %a{:href => "http://www.facebook.com/olesinski.przemyslaw", :target => "_blank", :title => "Facebook"} Facebook
          %li.googleplus
            %a{:href => "http://plus.google.com/+PrzemysławOlesiński/", :target => "_blank", :title => "Twitter"} Twitter
          %li.linkedin
            %a{:href => "http://www.linkedin.com/in/przemyslawolesinski/", :target => "_blank", :title => "Linkedin"} Linkedin
      %nav.nav-main.mega-menu
        %ul#mainMenu.nav.nav-pills.nav-main
          %li{:class => active_link_to(root_path)}
            = link_to "Strona główna", root_path
          %li{:class => active_link_to(about_path)}
            = link_to "O mnie", about_path
          %li{:class => active_link_to(projects_path)}
            = link_to "Projekty", projects_path
          / %li
          /   = link_to "Open Source", ""
          %li{:class => active_link_to(opinions_path)}
            = link_to "Opinie", opinions_path
          %li{:class => active_link_to(posts_path)}
            = link_to "Blog", posts_path
          %li{:class => active_link_to(contact_path)}
            = link_to "Kontakt", contact_path

app/views/layouts/_noty.html.erb
<% if notice.present? %>
    <script>
        noty({text: "<%= notice %>", timeout: 3000, layout: 'bottom', type: 'success'});
    </script>
<% end %>
<% if alert.present? %>
    <script>
        noty({text: "<%= alert %>", timeout: 3000, layout: 'bottom', type: 'error'});
    </script>
<% end %>

app/views/layouts/admin.html.haml
!!!
%html{"data-ember-extension" => "1", :lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %link{:href => "favicon.ico", :rel => "icon"}/
    %title Admin | Przemysław Olesiński
    = stylesheet_link_tag "//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"
    = stylesheet_link_tag "admin"
    = javascript_include_tag "//code.jquery.com/jquery-1.11.1.min.js"
    = javascript_include_tag "//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"
    = javascript_include_tag "admin"
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse{:role => "navigation"}
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to "Admin", admin_root_path
            %li 
              = link_to "Projekty", admin_projects_path
            %li 
              = link_to "Tagi", admin_project_tags_path
            %li 
              = link_to "Kategorie projektów", admin_project_categories_path
            %li 
              = link_to "Strony", admin_pages_path
            %li 
              = link_to "Posty", admin_posts_path
            %li 
              = link_to "Kategorie postów", admin_post_categories_path
            %li 
              = link_to "Opinie", admin_opinions_path
          %ul.nav.navbar-nav.navbar-right
            %li
              = link_to "Wyloguj", destroy_user_session_path, method: :delete
    .clearfix
    .container
      = yield
    = render "layouts/noty"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]>      <html class="ie ie8"> <![endif]-->
<!--[if IE 9]>      <html class="ie ie9"> <![endif]-->
<!--[if gt IE 9]><!-->  <html> <!--<![endif]-->
  <head>

    <!-- Basic -->
    <meta charset="utf-8">
    <title><%= content_for?(:title) ? yield(:title) : "Web Developer | Przemysław Olesiński" %></title>
    <meta name="keywords" content="<%= content_for?(:keywords) ? yield(:keywords) : "portfolio, web design, darmowe szkolenia" %>" />
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Web Developer | Przemysław Olesiński" %>">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Web Fonts  -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

    <!-- Libs CSS -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/fonts/font-awesome/css/font-awesome.css">
    <link rel="stylesheet" href="/vendor/owl-carousel/owl.carousel.css" media="screen">
    <link rel="stylesheet" href="/vendor/owl-carousel/owl.theme.css" media="screen">
    <link rel="stylesheet" href="/vendor/magnific-popup/magnific-popup.css" media="screen">
    <link rel="stylesheet" href="/vendor/isotope/jquery.isotope.css" media="screen">

    <!-- Theme CSS -->
    <link rel="stylesheet" href="/css/theme.css">
    <link rel="stylesheet" href="/css/theme-elements.css">
    <link rel="stylesheet" href="/css/theme-animate.css">

    <!-- Current Page Styles -->
    <link rel="stylesheet" href="/vendor/rs-plugin/css/settings.css" media="screen">
    <link rel="stylesheet" href="/vendor/circle-flip-slideshow/css/component.css" media="screen">

    <!-- Skin CSS -->
    <link rel="stylesheet" href="/css/skins/blue.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="/css/custom.css">

    <!-- Responsive CSS -->
    <link rel="stylesheet" href="/css/theme-responsive.css" />

    <!-- Head Libs -->
    <script src="/vendor/modernizr.js"></script>
    
    <%= stylesheet_link_tag "application" %>

    <!--[if IE]>
      <link rel="stylesheet" href="/css/ie.css">
    <![endif]-->

    <!--[if lte IE 8]>
      <script src="/vendor/respond.js"></script>
    <![endif]-->
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="body">
      <%= render 'layouts/nav' %>

      <%= yield %>

      <%= render 'layouts/footer' %>
      <%= render 'layouts/noty' %>
    </div>
     <!-- Libs -->
    <script src="/vendor/jquery.js"></script>
    <script src="/js/plugins.js"></script>
    <script src="/vendor/jquery.easing.js"></script>
    <script src="/vendor/jquery.appear.js"></script>
    <script src="/vendor/jquery.cookie.js"></script>
    <%= javascript_include_tag "application" %>

    <script src="/vendor/bootstrap.js"></script>
    <script src="/vendor/rs-plugin/js/jquery.themepunch.plugins.min.js"></script>
    <script src="/vendor/rs-plugin/js/jquery.themepunch.revolution.js"></script>
    <script src="/vendor/owl-carousel/owl.carousel.js"></script>
    <script src="/vendor/circle-flip-slideshow/js/jquery.flipshow.js"></script>
    <script src="/vendor/magnific-popup/magnific-popup.js"></script>
    
    <!-- Current Page Scripts -->
    <script src="/js/views/view.home.js"></script>
    <script src="/vendor/jquery.validate.js"></script>

    <script src="/vendor/isotope/jquery.isotope.js"></script>

    <!-- Theme Initializer -->
    <script src="/js/theme.js"></script>

    <!-- Custom JS -->
    <script src="/js/custom.js"></script>
    <%= yield(:js) %>
  
  </body>
</html>

app/views/layouts/share/_post_categoty.html.haml
%h4 Kategorie
%ul.nav.nav-list.primary.push-bottom
  - PostCategory.all.each do |c|
    %li
      = link_to c.name, post_category_path(c)