config/routes.rb
Rails.application.routes.draw do


  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root 'frontend#index'

  get "/admin", to: "admin#index", as: :admin_root


  namespace :admin do 
    resources :projects
    resources :project_tags
    resources :project_categories
    resources :posts
    resources :post_categories
    resources :pages
    resources :opinions
  end

  get "/contact", to: "frontend#contact", as: :contact
  get "/about-me", to: "frontend#about", as: :about
  post "/contact", to: "frontend#send_contact", as: :send_contact
  resources :projects, only: [:index, :show]
  resources :posts, only: [:index, :show]
  resources :opinions, only: [:index, :show]
  resources :post_categories, only: [:show]

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/post.rb
class Post < ActiveRecord::Base

  mount_uploader :image, PostPhotoUploader

  default_scope { order('created_at DESC') }
   
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_and_belongs_to_many :post_categories

  self.per_page = 10
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name, use: :slugged
  has_and_belongs_to_many :posts
end

app/models/project.rb
class Project < ActiveRecord::Base

  mount_uploader :image, ProjectPhotoUploader
  default_scope { order('created_at DESC') }

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_and_belongs_to_many :project_tags
  has_and_belongs_to_many :project_categories
  has_many :project_images
  accepts_nested_attributes_for :project_images, :reject_if => :all_blank, :allow_destroy => true
end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name, use: :slugged
  has_and_belongs_to_many :projects
end

app/models/project_image.rb
class ProjectImage < ActiveRecord::Base

  mount_uploader :foto, ProjectUploader

  belongs_to :project
end

app/models/project_tag.rb
class ProjectTag < ActiveRecord::Base

  IMG = [
        "Sass" => "sass.png", 
        "jQuery" => "jquery.png", 
        "CoffyScript" => "coffy.png", 
        "WordPress" => "wordpress.png", 
        "PHP" => "php.png", 
        "AngularJs" => "angularjs.png",
        "Symfony 2" => "symfony.png",
        "Magento" => "magento.jpg", 
        "Ruby on Rails" => "rails.jpg",
        "Joomla" => "joomla.png",
        "Sinatra" => "sinatra.png",
        "PayU" => "payu.jpg",
        "MySql" => "mysql.png",
        "PostgreSQL" => "postgresql.png",
        "PayPal Api" => "paypal.jpg",
        "LinkedIn Api" => "linkedin.jpg", 
        "Google Maps Api" => "google-maps.png",
        "Amazon" => "amazon.jpg",
        "Android" => "android.png",
        "Bootstrap" => "bootstrap.jpg",
        "Capistrano" => "capistrano.png",
        "Cucumber" => "cucumber.png",
        "D3.js" => "d3js-logo.jpg",
        "DigitalOcean" => "do.jpg",
        "Fb API" => "fb-api.png",
        "Font Awesome" => "font-awesome-logo.png",
        "foundation" => "foundation.jpg",
        "Google Plus Api" => "google_plus_api.jpg",
        "Heroku" => "heroku.jpg",
        "jQuery Mobile" => "jquery-mobile.png",
        "Object C" => "objectc.jpg",
        "RSpec" => "rspec.jpg",
        "Ruby" => "ruby.png",
        "Sassu" => "sassu.jpg",
        "Spree" => "spree.jpg",
        "Stripe" => "stripe.png"
    ]

  extend FriendlyId
  friendly_id :name, use: :slugged
  has_and_belongs_to_many :projects
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < AdminController

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index 
    @projects = Project.all
  end

  
  def show
  end

  def new
    @project = Project.new
  end

  def create
     @project = Project.new(project_params)
    if @project.save
      redirect_to edit_admin_project_path(@project), notice: "Dodano projekt"
    else
      render action: "new"
    end
  end

  def edit
    
  end

  def update
    if @project.update_attributes(project_params)
      redirect_to edit_admin_project_path(@project), notice: "Projekt zapisany"
    else
      render action: "edit"
    end
  end

  def destroy 
    if @project.delete
      redirect_to admin_projects_path, notice: "Project usuniety"
    else
      redirect_to admin_projects_path, notice: "Wystapil problem przy usuaniu"
    end
  end

  protected

  def set_project
    @project = Project.friendly.find(params[:id])  
  end

  def project_params
    params.require(:project).permit(:title, :keywords, :description, :what_i_did, :about, :content, :link, :image, :startup, :open_source, project_category_ids: [], project_tag_ids: [], project_images_attributes: [:id, :foto, :_destroy])
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	before_action :authenticate_user!
	before_action :check_permision!

	layout "admin"

	def index
	end

	protected

	def check_permision!
		unless current_user.has_role :admin
			redirect_to :root_path
		end
	end

end

app/controllers/amin_controller.rb
class AdminController < ApplicationController

	before_action :authenticate_user!
	before_action :check_permision

	def index
	end

	protected

	def check_permision!
		unless current_user.has_role :admin
			redirect_to :root_path
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  def index
    @posts = Post.all.limit(4)
    @opinions  = Opinion.all.limit(2)
  end

  def contact
    @contact = Contact.new
  end

  def send_contact
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to contact_path, notice: "Wiadomość wysłana"
    else
      render action: "contact"
    end
  end

  def about
    @tags = ProjectTag.all
  end

  protected 

  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController 

  def index
    @opinions = Opinion.all
  end

  def show
  end

end

app/controllers/post_categories_controller.rb
class PostCategoriesController < ApplicationController
  def show
    @category = PostCategory.friendly.find(params[:id])
    @posts = @category.posts.paginate(:page => params[:page])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 

  def index
    @posts = Post.paginate(:page => params[:page])
  end

  def show
    @post = Post.friendly.find(params[:id])  
  end

  

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show]

  def index 
    @projects = Project.all
    @categories = ProjectCategory.all
    @tags = ProjectTag.all
  end

  
  def show
  end

  protected

  def set_project
    @project = Project.friendly.find(params[:id])  
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_link_to(options = {}, html_options = {}, &block)
    active_class = html_options[:active] || "active"
    html_options.delete(:active)
    html_options[:class] = "#{html_options[:class]} #{active_class}" if current_page?(options)

  end

  def tag_to_img(tag)
    image_tag ProjectTag::IMG[0][tag], title: tag, alt: tag
  end
end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/views/admin/projects/_form.html.haml
= simple_form_for [:admin, @project], :html => {class: "form-horizontal"} do |f|
  .form-group
    = f.label :title, class: "col-sm-2 control-label"
    .col-sm-10
      = f.input_field :title, label: false, class: "form-control"
  .form-group
    = f.label :keywords, class: "col-sm-2 control-label"
    .col-sm-10
      = f.input_field :keywords, label: false, class: "form-control"
  .form-group
    = f.label :description, class: "col-sm-2 control-label"
    .col-sm-10
      = f.input_field :description, label: false, class: "form-control"
  .form-group
    = f.label :what_i_did, class: "col-sm-2 control-label"
    .col-sm-10
      = f.input_field :what_i_did, label: false, class: "form-control"
  .form-group
    = f.label :about, class: "col-sm-2 control-label"
    .col-sm-10
      = f.input_field :about, label: false, class: "form-control"
  .form-group
    = f.label :content, class: "col-sm-2 control-label"
    .col-sm-10
      = f.input_field :content, label: false, class: "form-control"
  .form-group
    = f.label :link, class: "col-sm-2 control-label"
    .col-sm-10
      = f.input_field :link, label: false, class: "form-control"

  .form-group
    = f.label :image , class: "col-sm-2 control-label"
    .col-sm-10
      - if @project.id.present?
        = image_tag @project.image, class: "img-responsive"
      = f.input_field :image , label: false, class: "form-control"
  = f.simple_fields_for :project_images do |project_image|
    = render 'project_image_fields', :f => project_image
  .form-group.links
    .col-sm-offset-2.col-sm-10
      = link_to_add_association 'add image', f, :project_images
  .form-group
    %label.col-sm-2.control-label Kategorie 
    .col-sm-10
      = f.association :project_categories , label: false, input_html: {class: "select2", style: "width: 100%;"}
  .form-group
    %label.col-sm-2.control-label Tagi
    .col-sm-10
      = f.association :project_tags , label: false, input_html: {class: "select2", style: "width: 100%;"}
  .col-sm-offset-2.col-sm-10
    .checkbox
      %label
        = f.input_field :open_source, label: false
        Open Source
  .col-sm-offset-2.col-sm-10
    .checkbox
      %label
        = f.input_field :startup, label: false
        StartUp
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.button :submit, "Zapisz" , class: "btn btn-default"

app/views/admin/projects/_project_image_fields.html.haml
.nested-fields.form-group
  = f.label :foto, "link do zdjecia" , class: "col-sm-2 control-label"
  .col-sm-5
    = image_tag f.object.foto
  .col-sm-4
    = f.input_field :foto
  .col-sm-1
    = link_to_remove_association "-", f

app/views/admin/projects/index.html.haml
= link_to "Dodaj projekt", new_admin_project_path, class: "btn btn-success"


%table.table
  %thead
    %tr
      %th Nazwa
      %th Link
      %th
  %tbody
    - @projects.each do |pt|
      %tr
        %td= pt.title
        %td= pt.slug
        %td{style: "width: 200px;"}
          -link_to raw(t('buttons.show_icon')), admin_project_path(pt), class: 'btn btn-default'
          =link_to raw(t('buttons.edit_icon')), edit_admin_project_path(pt), class: 'btn btn-success'
          =link_to raw(t('buttons.delete_icon')), admin_project_path(pt), method: :delete, data: { confirm: t('destroy.project') }, class: 'btn btn-danger'

app/views/projects/index.html.haml
.main
  %section.page-top
    .container
      .row
        .col-md-12
          %ul.breadcrumb
            %li
              %a{:href => "/"} Strona główna
            %li.active Projekty
      .row
        .col-md-12
          %h2 Wybrane projekty
  .container
    %ul.nav.nav-pills.sort-source{"data-option-key" => "filter", "data-sort-id" => "portfolio"}
      %li.active{"data-option-value" => "*"}
        %a{:href => "#"} Wszystkie
      - @categories.each do |c|
        %li{"data-option-value" => ".#{c.slug}"}
          %a{:href => "#"}= c.name
      %li.break{style: "width: 100%;"}
        %hr
        %p Kliknij ikonę technologii by zobaczyć wybrane projekty:
      - @tags.each do |c|
        - if c.projects.length > 0
          %li{"data-option-value" => ".#{c.slug}"}
            %a{:href => "#"}= tag_to_img c.name
    %hr
    .row
      %ul.portfolio-list.sort-destination.isotope{"data-sort-id" => "portfolio", :style => "position: relative; overflow: hidden; height: 529px;"} 
        - @projects.each do |p|
          %li{:style => "position: absolute; left: 0px; top: 0px; transform: translate3d(0px, 0px, 0px);", class: "col-md-3 isotope-item #{ p.project_categories.map(&:slug).join(' ') } #{ p.project_tags.map(&:slug).join(' ') }"}
            .portfolio-item.img-thumbnail
              = link_to project_path(p), class: "thumb-info" do
                = image_tag p.image, class: "img-responsive"
                %span.thumb-info-title
                  %span.thumb-info-inner= p.title
                  / %span.thumb-info-type Website
                %span.thumb-info-action
                  %span.thumb-info-action-icon{:href => "#", :title => "Universal"}
                    %i.icon.icon-link

app/views/projects/show.html.haml
.main
  %section.page-top
    .container
      .row
        .col-md-12
          %ul.breadcrumb
            %li
              %a{:href => "/"} Strona główna
            %li
              = link_to "Projekty", projects_path
            %li.active= @project.title
      .row
        .col-md-12
          %h2= @project.title
  .container
    .portfolio-title
      .row
        .portfolio-nav-all.col-md-1
          %a{"data-original-title" => "Back to list", :href => "#{projects_path}", :rel => "tooltip"}
            %i.icon.icon-th
        .col-md-10.center
          %h2.shorter= @project.title
    %hr.tall
    .row
      .col-md-4
        .owl-carousel.owl-theme.owl-carousel-init{"data-plugin-options" => "{\"items\": 1, \"autoHeight\": true}", :style => "display: block; opacity: 1;"}
          .owl-wrapper-outer.autoHeight{:style => "height: 376px;"}
            .owl-wrapper{:style => "width: 2160px; left: 0px; display: block;"}
              - if @project.project_images.count > 0
                - @project.project_images.each do |image|
                  .owl-item{:style => "width: 360px;"}
                    %div
                      .thumbnail
                        = image_tag image.foto.thumb, class: "img-responsive"
              - else
                .owl-item{:style => "width: 360px;"}
                  %div
                    .thumbnail
                      = image_tag @project.image, class: "img-responsive"
      .col-md-8
        %h4
          Opis
          %strong Projektu
        %p.taller= @project.about
        - if @project.link.length > 5
          %a.btn.btn-primary.btn-icon{:href => "#{@project.link}", target: "_blank"}
            %i.icon.icon-external-link>
            Online
          %span.arrow.hlb.appear-animation.rotateInUpLeft.appear-animation-visible{"data-appear-animation" => "rotateInUpLeft", "data-appear-animation-delay" => "800", :style => "-webkit-animation: 800ms;"}
        %ul.portfolio-details
          %li
            %p
              %strong Technologie:
            %ul.list.list-skills.icons.list-unstyled.list-inline
              - @project.project_tags.each do |t|
                %li
                  = tag_to_img t.name
    %hr.tall
    .row
      .col-md-6
        %h4
          Co 
          %strong Zrobiłem
        = raw @project.what_i_did
      .col-md-6
        %h4
          Więcej
          %strong Informacji
        = raw @project.content