config/routes.rb
Rails.application.routes.draw do


  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root 'frontend#index'

  get "/admin", to: "admin#index", as: :admin_root


  namespace :admin do 
    resources :projects
    resources :project_tags
    resources :project_categories
    resources :posts
    resources :post_categories
    resources :pages
    resources :opinions
  end

  get "/contact", to: "frontend#contact", as: :contact
  get "/about-me", to: "frontend#about", as: :about
  post "/contact", to: "frontend#send_contact", as: :send_contact
  resources :projects, only: [:index, :show]
  resources :posts, only: [:index, :show]
  resources :opinions, only: [:index, :show]
  resources :post_categories, only: [:show]

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/post.rb
class Post < ActiveRecord::Base

  mount_uploader :image, PostPhotoUploader

  default_scope { order('created_at DESC') }
   
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_and_belongs_to_many :post_categories

  self.per_page = 10
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name, use: :slugged
  has_and_belongs_to_many :posts
end

app/models/project.rb
class Project < ActiveRecord::Base

  mount_uploader :image, ProjectPhotoUploader
  default_scope { order('created_at DESC') }

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_and_belongs_to_many :project_tags
  has_and_belongs_to_many :project_categories
  has_many :project_images
  accepts_nested_attributes_for :project_images, :reject_if => :all_blank, :allow_destroy => true
end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name, use: :slugged
  has_and_belongs_to_many :projects
end

app/models/project_image.rb
class ProjectImage < ActiveRecord::Base

  mount_uploader :foto, ProjectUploader

  belongs_to :project
end

app/models/project_tag.rb
class ProjectTag < ActiveRecord::Base

  IMG = [
        "Sass" => "sass.png", 
        "jQuery" => "jquery.png", 
        "CoffyScript" => "coffy.png", 
        "WordPress" => "wordpress.png", 
        "PHP" => "php.png", 
        "AngularJs" => "angularjs.png",
        "Symfony 2" => "symfony.png",
        "Magento" => "magento.jpg", 
        "Ruby on Rails" => "rails.jpg",
        "Joomla" => "joomla.png",
        "Sinatra" => "sinatra.png",
        "PayU" => "payu.jpg",
        "MySql" => "mysql.png",
        "PostgreSQL" => "postgresql.png",
        "PayPal Api" => "paypal.jpg",
        "LinkedIn Api" => "linkedin.jpg", 
        "Google Maps Api" => "google-maps.png",
        "Amazon" => "amazon.jpg",
        "Android" => "android.png",
        "Bootstrap" => "bootstrap.jpg",
        "Capistrano" => "capistrano.png",
        "Cucumber" => "cucumber.png",
        "D3.js" => "d3js-logo.jpg",
        "DigitalOcean" => "do.jpg",
        "Fb API" => "fb-api.png",
        "Font Awesome" => "font-awesome-logo.png",
        "foundation" => "foundation.jpg",
        "Google Plus Api" => "google_plus_api.jpg",
        "Heroku" => "heroku.jpg",
        "jQuery Mobile" => "jquery-mobile.png",
        "Object C" => "objectc.jpg",
        "RSpec" => "rspec.jpg",
        "Ruby" => "ruby.png",
        "Sassu" => "sassu.jpg",
        "Spree" => "spree.jpg",
        "Stripe" => "stripe.png"
    ]

  extend FriendlyId
  friendly_id :name, use: :slugged
  has_and_belongs_to_many :projects
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index 
    @posts = Post.all
  end

  
  def show
  end

  def new
    @post = Post.new
  end

  def create
     @post = Post.new(post_params)
    if @post.save
      redirect_to admin_posts_path, notice: "Dodano projekt"
    else
      render action: "new"
    end
  end

  def edit
    
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to admin_posts_path, notice: "Projekt zapisany"
    else
      render action: "edit"
    end
  end

  def destroy 
    if @post.delete
      redirect_to admin_posts_path, notice: "post usuniety"
    else
      redirect_to admin_posts_path, notice: "Wystapil problem przy usuaniu"
    end
  end

  protected

  def set_post
    @post = Post.friendly.find(params[:id])  
  end

  def post_params
    params.require(:post).permit(:title, :keywords, :description, :what_i_did, :about, :content, :link, :image, :startup, :open_source, post_category_ids: [], post_tag_ids: [])
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	before_action :authenticate_user!
	before_action :check_permision!

	layout "admin"

	def index
	end

	protected

	def check_permision!
		unless current_user.has_role :admin
			redirect_to :root_path
		end
	end

end

app/controllers/amin_controller.rb
class AdminController < ApplicationController

	before_action :authenticate_user!
	before_action :check_permision

	def index
	end

	protected

	def check_permision!
		unless current_user.has_role :admin
			redirect_to :root_path
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  def index
    @posts = Post.all.limit(4)
    @opinions  = Opinion.all.limit(2)
  end

  def contact
    @contact = Contact.new
  end

  def send_contact
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to contact_path, notice: "Wiadomość wysłana"
    else
      render action: "contact"
    end
  end

  def about
    @tags = ProjectTag.all
  end

  protected 

  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController 

  def index
    @opinions = Opinion.all
  end

  def show
  end

end

app/controllers/post_categories_controller.rb
class PostCategoriesController < ApplicationController
  def show
    @category = PostCategory.friendly.find(params[:id])
    @posts = @category.posts.paginate(:page => params[:page])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 

  def index
    @posts = Post.paginate(:page => params[:page])
  end

  def show
    @post = Post.friendly.find(params[:id])  
  end

  

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show]

  def index 
    @projects = Project.all
    @categories = ProjectCategory.all
    @tags = ProjectTag.all
  end

  
  def show
  end

  protected

  def set_project
    @project = Project.friendly.find(params[:id])  
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def active_link_to(options = {}, html_options = {}, &block)
    active_class = html_options[:active] || "active"
    html_options.delete(:active)
    html_options[:class] = "#{html_options[:class]} #{active_class}" if current_page?(options)

  end

  def tag_to_img(tag)
    image_tag ProjectTag::IMG[0][tag], title: tag, alt: tag
  end
end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/views/posts/index.html.haml
.main
  %section.page-top
    .container
      .row
        .col-md-12
          %ul.breadcrumb
            %li
              %a{:href => "/"} Strona główna
            %li.active Wiadomości
      .row
        .col-md-12
          %h2 Wiadomości
  .container
    .row      
      .col-md-9
        .blog-posts
          - @posts.each do |p|
            %article.post.post-medium
              .row
                .col-md-5
                  .post-image
                    .owl-carousel.owl-theme.owl-carousel-init{"data-plugin-options" => "{\"items\":1}", :style => "display: block; opacity: 1;"}
                      .owl-wrapper-outer
                        .owl-wrapper{:style => "width: 1344px; left: 0px; display: block;"}
                          .owl-item{:style => "width: 336px;"}
                            %div
                              .img-thumbnail
                                = image_tag p.image, class: "img-responsive" 
                .col-md-7
                  .post-content
                    %h2
                      = link_to p.title, post_path(p)
                    = truncate(p.content, length: 400, separator: ' ', escape: false)
              .row
                .col-md-12
                  .post-meta
                    %span
                      %i.icon.icon-calendar
                      = l p.created_at, :format => :long
                    = link_to "Czytaj więcej", post_path(p), class: "btn btn-xs btn-primary pull-right" 

        = will_paginate @posts
           

app/views/posts/show.html.haml
.main
  %section.page-top
    .container
      .row
        .col-md-12
          %ul.breadcrumb
            %li
              %a{:href => "/"} Strona główna
            %li
              = link_to "Wiadomości", posts_path
            %li.active= @post.title
      .row
        .col-md-12
          %h2= @post.title
  .container
    .row
      .col-md-9
        .blog-posts.single-post
          %article.post.post-large.blog-single-post
            .post-image
              .owl-carousel.owl-theme.owl-carousel-init{"data-plugin-options" => "{\"items\":1}", :style => "display: block; opacity: 1;"}
                .owl-wrapper-outer
                  .owl-wrapper{:style => "width: 3392px; left: 0px; display: block;"}
                    .owl-item{:style => "width: 848px;"}
                      %div
                        .img-thumbnail
                          = image_tag @post.image, class: "img-responsive"
            .post-content
              %hr.tell
              %h2= @post.title
              = raw @post.content
      .col-sm-3
        = render 'layouts/share/post_categoty'